# Default values for couch-load-mk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# used for the batch Kubernetes job to connect to CouchDB and load sample records
dbload:
  image:
    repository: ibmcase/bluecompute-bash-curl-ssl
    tag: latest
  dbService:
    minikubeIP: 9.30.45.132
    port: 31111