apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: icp-test
    micro: provider
    tier: middle
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: icp-test
        micro: provider
        tier: middle
    spec:
      containers:
      - name: provider
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ int .Values.service.internalPort }}
        env:
        - name: PORT-TEST # for some reason we can't seem to pass an integer in as the value here
          value: dummy
        resources:
{{ toYaml .Values.resources | indent 12 }}
