# Default values for micro-provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: mycluster.icp:8500/default/icp-test-prov-db
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: p-svc
  type: NodePort
  externalPort: 30099
  internalPort: 8080

tags:
  app-role: provider

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

environment:
  testData: this-is-just-a-test