# Default values for micro-consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: icp-test/consumer
  tag: latest
  pullPolicy: Never

service:
  name: c-svc
  type: NodePort
  externalPort: 30098
  internalPort: 8080

tags:
  app-role: consumer

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

# Probably need a better way of doing this with entries for releaseName plus service name etc
# prov-p-svc prov-p-svc.default prov-p-svc.default.svc.cluster.local
# Works: 192.168.1.199
# Fails: prov-p-svc
# Might be an issue trying to use a value that is not a string
dependencies:
  providerService: prov-p-svc.default.svc.cluster.local