# Default values for micro-consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: mycluster.icp:8500/default/icp-test-consumer
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: c-svc
  type: NodePort
  externalPort: 30098
  internalPort: 8080

tags:
  app-role: consumer

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

# Probably need a better way of doing this with entries for releaseName plus service name etc
# Try p-svc, p-svc.default.svc.cluster.local 9.20.194.58
dependencies:
  providerEndpoint: 9.20.194.58
  providerPort: 30099